[pytest]
asyncio_mode = strict
filterwarnings =
    ignore::DeprecationWarning:starlette.formparsers.*
    ignore::PendingDeprecationWarning:starlette.formparsers.*
    ignore::DeprecationWarning:pydantic.*
    ignore::PendingDeprecationWarning:pydantic.*
